-- DARADIFF online join-request setup
-- Run this entire file in Supabase -> SQL Editor -> Run.

create table if not exists public.join_requests (
  id bigint generated by default as identity primary key,
  name text not null,
  fb text default '#',
  role text not null check (role in ('Founder','Leader','SUP','Member')),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  fb text default '#',
  section text not null check (section in ('leadership','sup','member')),
  created_at timestamptz not null default now()
);

alter table public.join_requests enable row level security;
alter table public.people enable row level security;

drop policy if exists "public can submit join requests" on public.join_requests;
create policy "public can submit join requests"
on public.join_requests for insert to anon, authenticated
with check (status = 'pending');

drop policy if exists "public can view pending join requests" on public.join_requests;
create policy "public can view pending join requests"
on public.join_requests for select to anon, authenticated
using (status = 'pending');

drop policy if exists "public can delete join requests" on public.join_requests;
create policy "public can delete join requests"
on public.join_requests for delete to anon, authenticated
using (true);

drop policy if exists "public can add approved people" on public.people;
create policy "public can add approved people"
on public.people for insert to anon, authenticated
with check (section in ('leadership','sup','member'));

drop policy if exists "public can view people" on public.people;
create policy "public can view people"
on public.people for select to anon, authenticated
using (true);

-- Note: this static HTML app still uses its existing client-side Admin password.
-- For stronger security, add Supabase Auth later and restrict admin operations by user role.


-- Allow the browser Admin Panel to delete approved people.
drop policy if exists "public can delete people" on public.people;
create policy "public can delete people"
on public.people for delete to anon, authenticated
using (true);

-- Realtime + browser Admin edit support.
drop policy if exists "public can update people" on public.people;
create policy "public can update people"
on public.people for update to anon, authenticated
using (true)
with check (section in ('leadership','sup','member'));

-- Enable Realtime for the two shared tables used by the website.
alter table public.people replica identity full;
alter table public.join_requests replica identity full;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'people'
  ) THEN
    EXECUTE 'alter publication supabase_realtime add table public.people';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'join_requests'
  ) THEN
    EXECUTE 'alter publication supabase_realtime add table public.join_requests';
  END IF;
END $$;
